language:
  - cpp

compiler:
  - gcc
  - clang

install:
  - sudo sh -c 'echo deb http://unv-debs.moreofthesa.me.uk precise main >>/etc/apt/sources.list'
  - sudo apt-key adv --keyserver x-hkp://pool.sks-keyservers.net --recv-key 06AF4C14
  - sudo sh -c 'echo deb http://ppa.launchpad.net/purplekarrot/ppa/ubuntu precise main >>/etc/apt/sources.list'
  - sudo apt-key adv --keyserver x-hkp://pool.sks-keyservers.net --recv-key D4762858
  - sudo apt-get -qq update
  - sudo apt-get -qq install libwebp-dev libglew-dev libgmp-dev libjpeg8-dev libcurl4-gnutls-dev libfreetype6-dev libgeoip-dev libncursesw5-dev libogg-dev libopenal-dev libpng-dev libsdl1.2-dev libspeexdsp-dev libtheora-dev libvorbis-dev libopusfile-dev libxvidcore-dev nettle-dev zlib1g-dev cmake

before_script:
  - wget http://clang.llvm.org/libstdc++4.6-clang11.patch;
  - wget "http://gcc.gnu.org/viewcvs/gcc/branches/gcc-4_7-branch/libstdc%2B%2B-v3/include/std/condition_variable?view=patch&r1=193528&r2=193527&pathrev=193528" -O libstdc++4.6-thread-fix.patch
  - sudo patch /usr/include/c++/4.6/type_traits < libstdc++4.6-clang11.patch;
  - sudo patch /usr/include/c++/4.6/condition_variable < libstdc++4.6-thread-fix.patch;

script:
  - sed -i s/POSITION_INDEPENDENT_CODE/COMPILE_FLAGS "-fPIC"/' CMakeLists.txt
  - mkdir build
  - cd build
  - CXXFLAGS="-D__extern_always_inline=inline" cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_SDL2=OFF ..
  - cmake --build .

notifications:
  irc:
    - "irc.freenode.org#unvanquished-dev"
    - "irc.quakenet.org#unvanquished"
  on_success: change
  on_failure: always

branches:
  except:
    - debian
    - engine-upgrade/sound
