#ifndef BIGPLATFORM_COMPONENT_H_
#define BIGPLATFORM_COMPONENT_H_

#include "../backend/CBSEBackend.h"
#include "../backend/CBSEComponents.h"

class BigPlatformComponent: public BigPlatformComponentBase {
	public:
		// ///////////////////// //
		// Autogenerated Members //
		// ///////////////////// //

		/**
		 * @brief Default constructor of the BigPlatformComponent.
		 * @param entity The entity that owns the component instance.
		 * @param r_HumanBuildableComponent A HumanBuildableComponent instance that this component depends on.
		 * @note This method is an interface for autogenerated code, do not modify its signature.
		 */
		BigPlatformComponent(Entity& entity, HumanBuildableComponent& r_HumanBuildableComponent);

		// ///////////////////// //

		void CleanUp();
		void StartRound(const std::vector<gentity_t*>& players);
		void Bounds(vec3_t mins, vec3_t maxs);

	private:
		void AddCrates(int timeDelta);
		void Countdown(int timeDelta);
		void Place(gentity_t* player, int position);
		void ImmobilizePlayers(int timeDelta);
		void CheckWinner(int timeDelta);

		bool playing_ = false;
		int countdown_;
		std::array<GentityRef, 4> players_;
};

#endif // BIGPLATFORM_COMPONENT_H_
