#ifndef HEALTHITEM_COMPONENT_H_
#define HEALTHITEM_COMPONENT_H_

#include "../backend/CBSEBackend.h"
#include "../backend/CBSEComponents.h"

class HealthItemComponent: public HealthItemComponentBase {
	public:
		// ///////////////////// //
		// Autogenerated Members //
		// ///////////////////// //

		/**
		 * @brief Default constructor of the HealthItemComponent.
		 * @param entity The entity that owns the component instance.
		 * @param r_ThinkingComponent A ThinkingComponent instance that this component depends on.
		 * @note This method is an interface for autogenerated code, do not modify its signature.
		 */
		HealthItemComponent(Entity& entity, ThinkingComponent& r_ThinkingComponent);

		// ///////////////////// //

	private:
		void CheckPickup(int timeDelta);
};

#endif // HEALTHITEM_COMPONENT_H_
